{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "mail-and-media-shop.fullname" . }}-vault-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mail-and-media-shop.labels" . | nindent 4 }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ include "mail-and-media-shop.fullname" . }}-vault-backend
    kind: SecretStore
  target:
    name: {{ include "mail-and-media-shop.fullname" . }}-vault-app-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: mam-shop/{{ .Values.global.environment | default "dev" }}
{{- end }}
