{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "mail-and-media-shop.fullname" . }}-vault-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mail-and-media-shop.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | default "https://192.168.56.10:8200" | quote }}
      path: "secret"
      version: "v2"
      {{- if and .Values.vault.caProvider .Values.vault.caProvider.enabled }}
      caProvider:
        type: {{ .Values.vault.caProvider.type | default "ConfigMap" | quote }}
        name: {{ .Values.vault.caProvider.name | default "vault-ca" | quote }}
        key: {{ .Values.vault.caProvider.key | default "ca.crt" | quote }}
      {{- else if .Values.vault.caBundle }}
      caBundle: {{ .Values.vault.caBundle | quote }}
      {{- end }}
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: {{ .Values.vault.role | default "mam-shop-role" | quote }}
{{- end }}
