{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "mail-and-media-shop.fullname" . }}-vault-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mail-and-media-shop.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | default "http://192.168.56.10:8200" | quote }}
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: {{ .Values.vault.role | default "mam-shop-role" | quote }}
{{- end }}
